[package]
name = "lambda-rush"
version = "0.1.0"
authors = ["MislankaNova <mislankanova@hotmail.com>"]

[dependencies]
rand = "0.3"

[dependencies.sfml]
version="0.11"

[lib]
name = "rush"
path = "src/lib.rs"
